# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161127_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='current_floor',
        ),
    ]
